# app config
spring:
  application:
    name: api-gateway-server
# spring cloud gateway config
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
# eureka discovery client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


# server config
server:
  port: 8443

